name: drupalnext

services:
  node:
    type: node:14
    port: 3000
    command: npm run dev

proxy:
  node:
    - drupalnext.lndo.site:3000

tooling:
  yarn:
    service: node
  node:
    service: node
  npm:
    service: node